# Copyright (c) 2026, Mohammed Anas and contributors
# For license information, please see license.txt

"""Self-contained NIC / GSP e-Waybill HTTP client.

Replicates the Resilient Tech contract used by india_compliance
(`gst_india/api_classes/base.py` + `nic/e_waybill.py`) natively, with NO
runtime dependency on erpnext / india_compliance. The client NEVER raises:
every outcome (HTTP error, network failure, GSP `{"success": false}` body)
is folded into the returned dict so callers can log + msgprint instead of
handling exceptions.
"""

import frappe
import requests

from yrp_ewaybill_api.yrp_e_waybill_integration.doctype.yrp_e_waybill_settings.yrp_e_waybill_settings import (
	get_ewb_settings,
)

# NIC e-Waybill API actions (query param `action`).
GENERATE_ACTION = "GENEWAYBILL"
CANCEL_ACTION = "CANEWB"
UPDATE_VEHICLE_ACTION = "VEHEWB"
GET_BY_DATE_ACTION = "GetEwayBillsByDate"

EWAYBILL_PATH = "/ewb/ewayapi"
REQUEST_TIMEOUT = 30

# Resilient Tech / NIC sandbox test identity. The GSP sandbox ONLY accepts these
# credentials (and this GSTIN in the payload); real portal logins work only in
# production. Ported from india_compliance (nic/e_waybill.py sandbox override).
SANDBOX_GSTIN = "05AAACG2115R1ZN"
SANDBOX_USERNAME = "05AAACG2115R1ZN"
SANDBOX_PASSWORD = "abc123@@"


class EWaybillAPI:
	"""GSP e-Waybill client for a single company GSTIN.

	Reads connection + credentials from `YRP E-Waybill Settings`. Build once
	per company GSTIN, then call `generate` / `cancel` / `update_vehicle`.
	"""

	def __init__(self, company_gstin):
		self.company_gstin = company_gstin
		self.settings = get_ewb_settings()
		self.sandbox_mode = bool(self.settings.sandbox_mode)
		self.api_base_url = (self.settings.api_base_url or "").rstrip("/")
		# Credential is resolved lazily inside get_headers() (called within the
		# _request try/except) so a missing credential is captured as a failure
		# dict rather than raising out of the action — preserving never-raise.

	# --- public actions -------------------------------------------------

	def generate(self, payload):
		return self._request(GENERATE_ACTION, payload)

	def cancel(self, payload):
		return self._request(CANCEL_ACTION, payload)

	def update_vehicle(self, payload):
		return self._request(UPDATE_VEHICLE_ACTION, payload)

	def get_ewaybills_by_date(self, date):
		"""Fetch e-Waybills generated by this GSTIN on `date` (dd/mm/yyyy).
		Used to recover / link an already-generated e-Waybill (a GET action)."""
		return self._request(GET_BY_DATE_ACTION, None, method="GET", extra_params={"date": date})

	def get_ewaybill(self, ewb_no):
		"""Fetch the FULL e-Waybill detail for `ewb_no` (for printing). The
		sandbox action name is lowercase `getewaybill`; production is `GetEwayBill`."""
		action = "getewaybill" if self.sandbox_mode else "GetEwayBill"
		return self._request(action, None, method="GET", extra_params={"ewbNo": ewb_no})

	# --- request plumbing ----------------------------------------------

	def get_url(self, endpoint=""):
		"""`<api_base_url>[/test]/ewb/ewayapi[/endpoint]` (the `/test` segment in
		sandbox). GET (read) actions pass the action name as `endpoint` (a path
		segment); POST actions leave it empty and use a `?action=` query param."""
		prefix = "/test" if self.sandbox_mode else ""
		url = f"{self.api_base_url}{prefix}{EWAYBILL_PATH}"
		return f"{url}/{endpoint}" if endpoint else url

	def get_headers(self):
		api_secret = self.settings.get_password("api_secret") if self.settings.api_secret else None
		if self.sandbox_mode:
			# The GSP sandbox only accepts its own test login, not the real one.
			gstin, username, password = SANDBOX_GSTIN, SANDBOX_USERNAME, SANDBOX_PASSWORD
		else:
			# Raises if no credential is configured for this GSTIN — caught in _request.
			credential = self.settings.get_credential(self.company_gstin)
			gstin = self.company_gstin
			username = credential.get("username")
			password = credential.get("password")
		return {
			"x-api-key": api_secret,
			"gstin": gstin,
			"username": username,
			"password": password,
			"requestid": frappe.generate_hash(length=12),
			"Content-Type": "application/json",
		}

	def _request(self, action, payload, method="POST", extra_params=None):
		"""Send `payload` for `action` (POST by default, GET for read actions);
		return a normalised result dict.

		Shape: `{success, result, error, raw, status_code}`. `success` is True
		only when the HTTP status is 2xx AND the parsed body's `success` key is
		not explicitly False. Any exception is captured as `success=False`.
		"""
		result = {
			"success": False,
			"result": None,
			"error": None,
			"raw": None,
			"status_code": None,
		}

		try:
			if method == "GET":
				# GET (read) actions take the action as a URL PATH segment
				# (e.g. .../ewb/ewayapi/GetEwayBillsByDate?date=...), NOT ?action=.
				response = requests.get(
					self.get_url(action),
					params=dict(extra_params or {}),
					headers=self.get_headers(),
					timeout=REQUEST_TIMEOUT,
				)
			else:
				# POST actions take the action as a ?action= query param.
				params = {"action": action}
				if extra_params:
					params.update(extra_params)
				response = requests.post(
					self.get_url(),
					params=params,
					json=payload,
					headers=self.get_headers(),
					timeout=REQUEST_TIMEOUT,
				)

			result["status_code"] = response.status_code
			result["raw"] = response.text

			body = None
			try:
				body = response.json()
			except Exception:
				body = None

			if isinstance(body, dict):
				result["result"] = body.get("result")

			is_2xx = 200 <= (response.status_code or 0) < 300
			# Normalise the GSP `success` flag: a string "false"/"0" or numeric 0
			# must count as failure, not just the Python bool False (india_compliance
			# base.py runs it through sbool). Absent key defaults to True.
			body_success = True
			if isinstance(body, dict):
				sv = body.get("success", True)
				if isinstance(sv, str):
					sv = frappe.utils.sbool(sv)
				body_success = bool(sv)

			if is_2xx and body_success:
				result["success"] = True
			else:
				result["success"] = False
				result["error"] = self._extract_error(response, body)

		except Exception as e:
			result["success"] = False
			result["error"] = str(e)

		return result

	@staticmethod
	def _extract_error(response, body):
		if isinstance(body, dict):
			error = body.get("error") or body.get("message")
			if error:
				return frappe.as_json(error) if isinstance(error, (dict, list)) else str(error)
		return (getattr(response, "text", None) or "").strip() or f"HTTP {response.status_code}"
