# Copyright (c) 2026, Mohammed Anas and contributors
# For license information, please see license.txt

"""Unit tests for the self-contained NIC/GSP e-Waybill client.

Every test mocks `requests.post` (and the settings loader) so nothing hits
the network or the DB. Verifies the Resilient Tech URL/header contract and,
critically, that the client NEVER raises: HTTP errors, `{"success": false}`
bodies and network failures all fold into `{"success": False, ...}`.
"""

import json
import unittest
from unittest.mock import MagicMock, patch

from yrp_ewaybill_api.ewaybill import api as api_module
from yrp_ewaybill_api.ewaybill.api import EWaybillAPI

SANDBOX_GSTIN = "05AAACG2115R1ZN"


def _fake_settings(sandbox=True):
	settings = MagicMock()
	settings.sandbox_mode = 1 if sandbox else 0
	settings.api_base_url = "https://asp.resilient.tech"
	settings.api_secret = "encrypted-secret"
	settings.get_password.return_value = "my-secret-key"
	settings.get_credential.return_value = {"username": "testuser", "password": "testpass"}
	return settings


def _fake_response(status_code=200, body=None, text=None):
	response = MagicMock()
	response.status_code = status_code
	response.text = text if text is not None else json.dumps(body)
	if body is None and text is not None:
		response.json.side_effect = ValueError("no json")
	else:
		response.json.return_value = body
	return response


class TestEWaybillAPI(unittest.TestCase):
	def setUp(self):
		# Patch the settings loader used inside api.py so __init__ never hits the DB.
		patcher = patch.object(api_module, "get_ewb_settings", return_value=_fake_settings())
		self.mock_get_settings = patcher.start()
		self.addCleanup(patcher.stop)

	def test_generate_uses_sandbox_url_action_and_headers(self):
		body = {"success": True, "result": {"ewayBillNo": 123, "validUpto": "05/07/2026"}}
		with patch.object(api_module.requests, "post", return_value=_fake_response(200, body)) as mock_post:
			result = EWaybillAPI(SANDBOX_GSTIN).generate({"docNo": "DC-0001"})

		self.assertEqual(mock_post.call_count, 1)
		args, kwargs = mock_post.call_args
		url = args[0] if args else kwargs["url"]

		# Sandbox → /test/ segment; endpoint is /ewb/ewayapi.
		self.assertIn("/test/", url)
		self.assertTrue(url.endswith("/ewb/ewayapi"))
		# Action passed as a query param.
		self.assertEqual(kwargs["params"], {"action": "GENEWAYBILL"})
		# Auth + routing headers.
		headers = kwargs["headers"]
		# Sandbox overrides the login with the GSP test identity (not the real credential).
		self.assertEqual(headers["x-api-key"], "my-secret-key")
		self.assertEqual(headers["gstin"], SANDBOX_GSTIN)
		self.assertEqual(headers["username"], SANDBOX_GSTIN)
		self.assertEqual(headers["password"], "abc123@@")
		self.assertTrue(headers["requestid"])
		self.assertEqual(headers["Content-Type"], "application/json")
		self.assertEqual(kwargs["timeout"], 30)
		# Success surface.
		self.assertTrue(result["success"])
		self.assertEqual(result["result"], {"ewayBillNo": 123, "validUpto": "05/07/2026"})
		self.assertEqual(result["status_code"], 200)
		self.assertIsNone(result["error"])

	def test_non_2xx_body_false_returns_failure_without_exception(self):
		body = {"success": False, "error": "312: This eway bill is either not generated by you"}
		with patch.object(api_module.requests, "post", return_value=_fake_response(400, body)):
			# Must NOT raise.
			result = EWaybillAPI(SANDBOX_GSTIN).generate({"docNo": "DC-0002"})

		self.assertFalse(result["success"])
		self.assertEqual(result["status_code"], 400)
		self.assertTrue(result["error"])

	def test_success_false_on_2xx_is_failure(self):
		# HTTP 200 but the GSP body says success:false → overall failure.
		body = {"success": False, "message": "Invalid GSTIN"}
		with patch.object(api_module.requests, "post", return_value=_fake_response(200, body)):
			result = EWaybillAPI(SANDBOX_GSTIN).generate({"docNo": "DC-0003"})

		self.assertFalse(result["success"])
		self.assertIn("Invalid GSTIN", result["error"])

	def test_network_error_is_captured_not_raised(self):
		with patch.object(
			api_module.requests, "post", side_effect=api_module.requests.exceptions.ConnectionError("boom")
		):
			result = EWaybillAPI(SANDBOX_GSTIN).generate({"docNo": "DC-0004"})

		self.assertFalse(result["success"])
		self.assertIn("boom", result["error"])
		self.assertIsNone(result["status_code"])

	def test_cancel_uses_canewb_action(self):
		with patch.object(
			api_module.requests, "post", return_value=_fake_response(200, {"success": True, "result": {}})
		) as mock_post:
			EWaybillAPI(SANDBOX_GSTIN).cancel({"ewbNo": 123, "cancelRsnCode": 2})

		_, kwargs = mock_post.call_args
		self.assertEqual(kwargs["params"], {"action": "CANEWB"})

	def test_update_vehicle_uses_vehewb_action(self):
		with patch.object(
			api_module.requests, "post", return_value=_fake_response(200, {"success": True, "result": {}})
		) as mock_post:
			EWaybillAPI(SANDBOX_GSTIN).update_vehicle({"ewbNo": 123, "vehicleNo": "KA01AB1234"})

		_, kwargs = mock_post.call_args
		self.assertEqual(kwargs["params"], {"action": "VEHEWB"})

	def test_production_mode_has_no_test_segment(self):
		self.mock_get_settings.return_value = _fake_settings(sandbox=False)
		with patch.object(
			api_module.requests, "post", return_value=_fake_response(200, {"success": True, "result": {}})
		) as mock_post:
			EWaybillAPI(SANDBOX_GSTIN).generate({"docNo": "DC-0005"})

		args, kwargs = mock_post.call_args
		url = args[0] if args else kwargs["url"]
		self.assertNotIn("/test/", url)
		self.assertTrue(url.endswith("/ewb/ewayapi"))


if __name__ == "__main__":
	unittest.main()
