# Copyright (c) 2026, Mohammed Anas and contributors
# For license information, please see license.txt

"""Unit tests for the whitelisted e-Waybill actions.

Everything is mocked (no site / DB / network): `EWaybillAPI.generate` is patched
to return a success then an error dict, the doc + settings + log writer +
payload builder are stubbed. Asserts:
  - success  → `doc.ewaybill` set, `e_waybill_status="Generated"`, a Generated
               log row written, green toast, no exception.
  - failure  → `doc.ewaybill` stays unset, a **Failed** log row written (under a
               placeholder number), red toast, and NO exception propagates.
"""

import unittest
from unittest.mock import MagicMock, patch

import frappe

from yrp_ewaybill_api.ewaybill import actions as actions_module
from yrp_ewaybill_api.ewaybill import api as api_module
from yrp_ewaybill_api.ewaybill.actions import generate_e_waybill

COMPANY_GSTIN = "33AAACG2115R1ZN"


class _FakeDoc:
	"""Minimal stand-in for a submitted Delivery Challan."""

	def __init__(self):
		self.doctype = "Delivery Challan"
		self.name = "DC-0001"
		self.company_gstin = COMPANY_GSTIN
		self.ewaybill = None
		self.e_waybill_status = None

	def get(self, key, default=None):
		return getattr(self, key, default)

	def db_set(self, fieldname, value=None, **kwargs):
		if isinstance(fieldname, dict):
			for key, val in fieldname.items():
				setattr(self, key, val)
		else:
			setattr(self, fieldname, value)


def _fake_settings():
	settings = MagicMock()
	settings.sandbox_mode = 1
	settings.api_base_url = "https://asp.resilient.tech"
	settings.api_secret = "encrypted-secret"
	settings.get_password.return_value = "my-secret-key"
	settings.get_credential.return_value = {"username": "testuser", "password": "testpass"}
	return settings


class TestGenerateEWaybillAction(unittest.TestCase):
	def setUp(self):
		self.doc = _FakeDoc()

		# EWaybillAPI.__init__ reads settings via api_module.get_ewb_settings; the
		# action reads sandbox_mode via actions_module.get_ewb_settings.
		self._patchers = [
			patch.object(api_module, "get_ewb_settings", return_value=_fake_settings()),
			patch.object(actions_module, "get_ewb_settings", return_value=_fake_settings()),
			# Isolate from the (separately tested) payload builder + DB log writer.
			patch.object(actions_module, "build_generate_payload", return_value={"docNo": "DC-0001"}),
			patch.object(actions_module, "create_ewb_log"),
			# generate calls _ensure_gst_resolved → update_gst_details; stub it
			# (the fake doc already carries company_gstin).
			patch("yrp_ewaybill_api.gst.source_resolver.update_gst_details"),
			patch("frappe.has_permission", return_value=True),
			patch("frappe.get_doc", return_value=self.doc),
			patch("frappe.msgprint"),
		]
		for p in self._patchers:
			p.start()
			self.addCleanup(p.stop)
		self.create_ewb_log = actions_module.create_ewb_log
		self.msgprint = frappe.msgprint

	def _run_with_result(self, result):
		with patch.object(api_module.EWaybillAPI, "generate", return_value=result):
			return generate_e_waybill("Delivery Challan", "DC-0001", {"transporter_id": "T1"})

	def test_success_sets_ewaybill_and_writes_generated_log(self):
		result = {
			"success": True,
			"result": {"ewayBillNo": 331234567890, "validUpto": "2026-07-05 23:59:00"},
			"error": None,
			"status_code": 200,
		}
		out = self._run_with_result(result)

		# Doc updated.
		self.assertEqual(self.doc.ewaybill, "331234567890")
		self.assertEqual(self.doc.e_waybill_status, "Generated")
		self.assertEqual(out, {"ewaybill": "331234567890", "status": "Generated"})

		# A log row was written with the NIC number + Generated status.
		self.create_ewb_log.assert_called_once()
		kwargs = self.create_ewb_log.call_args.kwargs
		self.assertEqual(kwargs["e_waybill_number"], "331234567890")
		self.assertEqual(kwargs["status"], "Generated")
		self.assertEqual(kwargs["reference_doctype"], "Delivery Challan")
		self.assertEqual(kwargs["reference_name"], "DC-0001")

		# Green toast, no error toast.
		self.assertEqual(self.msgprint.call_args.kwargs.get("indicator"), "green")

	def test_part_a_when_no_validity_returned(self):
		result = {"success": True, "result": {"ewayBillNo": 331234567891}, "error": None}
		out = self._run_with_result(result)

		self.assertEqual(self.doc.ewaybill, "331234567891")
		self.assertEqual(self.doc.e_waybill_status, "Part A Generated")
		self.assertEqual(out["status"], "Part A Generated")

	def test_failure_does_not_throw_and_writes_failed_log(self):
		result = {
			"success": False,
			"result": None,
			"error": "312: This eway bill is either not generated by you",
			"status_code": 400,
		}

		# Must NOT raise.
		out = self._run_with_result(result)

		# Doc left untouched.
		self.assertIsNone(self.doc.ewaybill)
		self.assertIsNone(self.doc.e_waybill_status)
		self.assertEqual(out["status"], "Failed")
		self.assertIsNone(out["ewaybill"])

		# A Failed log row was written under a non-empty placeholder number.
		self.create_ewb_log.assert_called_once()
		kwargs = self.create_ewb_log.call_args.kwargs
		self.assertEqual(kwargs["status"], "Failed")
		self.assertEqual(kwargs["error"], "312: This eway bill is either not generated by you")
		self.assertTrue(kwargs["e_waybill_number"])

		# Red toast surfaced.
		self.assertEqual(self.msgprint.call_args.kwargs.get("indicator"), "red")

	def test_success_flag_but_missing_number_is_treated_as_failure(self):
		# GSP said success but returned no e-Waybill number → Failed, no throw.
		result = {"success": True, "result": {}, "error": None}
		out = self._run_with_result(result)

		self.assertIsNone(self.doc.ewaybill)
		self.assertEqual(out["status"], "Failed")
		self.create_ewb_log.assert_called_once()
		self.assertEqual(self.create_ewb_log.call_args.kwargs["status"], "Failed")


if __name__ == "__main__":
	unittest.main()
